services:
  - type: web
    name: aqi-predictor-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run gui_advanced.py --server.port $PORT
    envVars:
      - key: OPENWEATHER_API_KEY
        value: 2b51483b1a0ccbc850a3342a1abbfe5f